apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: ch20140270/customer:tagversion
        ports:
        - containerPort: 8443

---

kind: Service
apiVersion: v1
metadata:
  name:  customer
spec:
  selector:
    app:  customer
  type:  LoadBalancer
  ports:
  - name:  TCP
    port:  80
    targetPort:  8443